os: windows
# Travis CI Windows doesn't support java yet
language: shell

env:
  global:
    - JAVA_HOME="/c/Program Files/AdoptOpenJDK/jdk-11.0.8.10-hotspot"
    - ANT_HOME="/c/Users/travis/apache-ant"
    - PATH="$JAVA_HOME/bin:$ANT_HOME/bin:$PATH"

before_install:
  - pwd # /c/Users/travis/build/<github-user>/<repo-name>
  # Install the required JDK (must match JAVA_HOME in env: section)
  - choco install adoptopenjdk11
  - ls "/c/Program Files/AdoptOpenJDK" # Check JAVA_HOME is correct :(
  # Install ant at $ANT_HOME (chosen in env: section)
  - curl https://downloads.apache.org/ant/binaries/apache-ant-1.10.10-bin.zip -o apache-ant.zip
  - unzip -q apache-ant.zip
  - rm apache-ant.zip
  - mv apache-ant-1.10.10 $ANT_HOME

install:
  # Confirm versions and paths
  - echo $PATH
  - java -version
  - ant -version
  - cd gomule
  - ant Jar-BuildAllOptimezed